=== Azure-Samples/aoai-net-starterkit/assets/docs/03_SDK/sampleSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "address": {
        "type": "object",
        "properties": {
          "city": { "type": ["string", "null"] },
          "country": { "type": "string" },
          "postalCode": { "type": "string" },
          "state": { "type": ["string", "null"] },
          "street": { "type": ["string", "null"] }
        },
        "required": ["country", "postalCode"]
      },
      "contactDetails": {
        "type": "object",
        "properties": {
          "phone": { "type": ["string", "null"] }
        }
      },
      "currency": { "type": "string" },
      "customerId": { "type": "string" },
      "financials": {
        "type": "object",
        "properties": {
          "12MonthsSales": { "type": "number" },
          "add": { "type": "number" },
          "cei": { "type": ["number", "null"] },
          "creditMemos": { "type": "number" },
          "dso": { "type": "number" },
          "dueInvoices": { "type": "number" },
          "finScore": { "type": ["number", "null"] },
          "monthlyFinancials": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "add": { "type": ["number", "null"] },
                "cei": { "type": ["number", "null"] },
                "dso": { "type": ["number", "null"] },
                "invoices": { "type": "number" },
                "month": { "type": "number" },
                "openAR": { "type": "number" },
                "payments": { "type": "number" },
                "year": { "type": "number" }
              },
              "required": ["invoices", "month", "openAR", "year"]
            }
          },
          "overDueInvoices": { "type": "number" },
          "totalSales": { "type": "number" }
        },
        "required": ["12MonthsSales", "creditMemos", "dso", "dueInvoices", "monthlyFinancials", "overDueInvoices", "totalSales"]
      },
      "firstInvoiceDate": { "type": "string", "format": "date-time" },
      "foreignId": { "type": "string" },
      "name": { "type": "string" },
      "sectorNaicsDescription": { "type": ["string", "null"] },
      "sectorNaicsId": { "type": ["string", "null"] },
      "taxId": { "type": "string" },
      "verifiedName": { "type": ["string", "null"] }
    },
    "required": ["address", "currency", "customerId", "financials", "firstInvoiceDate", "foreignId", "name", "taxId"]
  }

=== Azure-Samples/aoai-net-starterkit/assets/docs/03_SDK/sampleObject.json
{
    "address": {
        "city": "boston",
        "country": "MEX",
        "postalCode": "22120",
        "state": null,
        "street": "harvard 123"
    },
    "contactDetails": {
        "phone": "123-456-7890"
    },
    "currency": "MXN",
    "customerId": "3759251",
    "financials": {
        "12MonthsSales": 378801.03,
        "add": 256,
        "cei": null,
        "creditMemos": 2701.53,
        "dso": 365,
        "dueInvoices": 113570.49,
        "finScore": null,
        "monthlyFinancials": [
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 18645.6,
                "month": 1,
                "openAR": 18645.6,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 13643.58,
                "month": 2,
                "openAR": 32289.18,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 25678.04,
                "month": 3,
                "openAR": 57967.22,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 4222.11,
                "month": 4,
                "openAR": 62189.33,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 16311.24,
                "month": 5,
                "openAR": -390529.82,
                "payments": 469030.39,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 17966.27,
                "month": 6,
                "openAR": -372563.55,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 17620.39,
                "month": 7,
                "openAR": -354943.16,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 27606.91,
                "month": 8,
                "openAR": -327336.25,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 26368.36,
                "month": 9,
                "openAR": -300967.89,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 42102.92,
                "month": 10,
                "openAR": -258864.97,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 35362.41,
                "month": 11,
                "openAR": -223502.56,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 17225.26,
                "month": 12,
                "openAR": -206277.3,
                "payments": 0.0,
                "year": 2020
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 40219.95,
                "month": 1,
                "openAR": -166057.35,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 18627.53,
                "month": 2,
                "openAR": -147429.82,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 39006.87,
                "month": 3,
                "openAR": -109268.31,
                "payments": 845.36,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 24313.79,
                "month": 4,
                "openAR": -84954.52,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 29120.05,
                "month": 5,
                "openAR": -55834.47,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 21769.73,
                "month": 6,
                "openAR": -34064.74,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 25222.36,
                "month": 7,
                "openAR": -8842.38,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 18040.4,
                "month": 8,
                "openAR": 9198.02,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 21790.66,
                "month": 9,
                "openAR": 30988.68,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 23711.27,
                "month": 10,
                "openAR": 54699.95,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 33641.38,
                "month": 11,
                "openAR": 88341.33,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 14485.61,
                "month": 12,
                "openAR": 102826.94,
                "payments": 0.0,
                "year": 2021
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 12264.25,
                "month": 1,
                "openAR": 114269.65,
                "payments": 821.54,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 18137.41,
                "month": 2,
                "openAR": 132407.06,
                "payments": 0.0,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 27155.51,
                "month": 3,
                "openAR": 159562.57,
                "payments": 0.0,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 39660.93,
                "month": 4,
                "openAR": 199223.5,
                "payments": 0.0,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 33279.23,
                "month": 5,
                "openAR": 232502.73,
                "payments": 0.0,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 55713.04,
                "month": 6,
                "openAR": 288215.77,
                "payments": 0.0,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 25679.26,
                "month": 7,
                "openAR": 313128.12,
                "payments": 766.91,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 36687.58,
                "month": 8,
                "openAR": 349809.4,
                "payments": 6.3,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 24697.81,
                "month": 9,
                "openAR": 374507.21,
                "payments": 0.0,
                "year": 2022
            },
            {
                "add": null,
                "cei": null,
                "dso": null,
                "invoices": 34601.75,
                "month": 10,
